### PR TITLE
9501 Kubernetes and OKE Monitoring and Troubleshooting

### PR DESCRIPTION
**Pull request by vikrredd**
# 9501

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please make sure all images have descriptive alternative texts in the Markdown files for accessibility.

**Comment by vikrredd** [comment]
> Hi! Please make sure all images have descriptive alternative texts in the Markdown files for accessibility.

Hi - Could you point me to the exact image where the changes are required, along with the example that would help. Thanks

**Comment by vikrredd** [comment]
Hi - Kindly point me to the exact image where the changes are required, along with the example that would help. Thanks

**Review by arabellayao — CHANGES_REQUESTED** [review]
Please see comments below.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! For example, Task 1 -> Step 2's image, the alt text should not be "Image alt text" but something descriptive, for example, "Log Explorer". Thanks!
Screen Shot 2022-09-13 at 11 33 08 AM

**Comment by vikrredd** [comment]
Updated the Image Alt Text

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
