### PR TITLE
WMS ID: 7921 + 9522 "Updated the title to match with rainfocus" 

### PR DESCRIPTION
**Pull request by Anand-GitH**
WMS ID: 7921

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Yes ] All filenames are lower case (including folders, images, files, etc.)
- [Yes] Filenames are descriptive
- [Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Yes] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Yes] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask someone from the workshop team to add you in WMS?

**Comment by Anand-GitH** [comment]
Hi Arabella, Yes Steve Lemme added me as observer for this workshop. Could you please go ahead and approve the request now.  

Thanks.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Your name is not listed as the workshop team member for #9522. Someone in the team needs to either add you as a workshop team member, or add your name in the "Notes and Additional Info" section. Thanks!

**Comment by Anand-GitH** [comment]
Hi Arabella, I got it updated as observer for the workshop #9522. Could you please approve now. 

Thanks.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
