### PR TITLE
updated lab title to match CW23 HOL title for sandbox

### PR DESCRIPTION
**Pull request by kgvarun**
WMS ID: 9501 / CW23 LL ID: 3805

### CODE REVIEW

**Comment by anooshapilli** [comment]
@kgvarun - There are no files changed in this PR. Could you check again?

**Comment by anooshapilli** [comment]
@kgvarun - Contacted over slack.

**Comment by anooshapilli** [comment]
@kgvarun - Followed up in Slack.

**Comment by kgvarun** [comment]
addressed elsewhere

**Pull request closed without merging**
