### PR TITLE
(#11775) New workshop from the DBA Essentials series - manage user accounts for 23ai

### PR DESCRIPTION
**Pull request by manish-garodia**
Hello,

We have developed a new workshop - Administer user accounts and security for Oracle Database 23ai, WMS ID is #11775.

Would be great if you approve this PR please so that we could proceed with publishing to production on priority.

Thanks for your help and support.

~mg

### CODE REVIEW

**Comment by anacoman11** [comment]
Hi @manish-garodia, sent you a DM

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @manish-garodia, please check the numbering of the steps from the following markdown files because it is incorrect:

- initialize-environment/initialize-environment.md
- manage-db-roles/manage-db-roles.md
- manage-db-users-accounts/manage-db-users-accounts.md
- prepare-setup/prepare-setup.md

**Comment by manish-garodia** [comment]
Hi Ana, 
I believe there is no issue... we have kept them all at number 1 because they are auto numbered... if we use a sequence - 1, 2, 3.. then any changes to the steps would require re-numbering and that's manual.. Therefore, we use the autonumbering option. The numbering in the html output is rendering correctly.

**Review by anacoman11 — APPROVED** [review]

**Comment by manish-garodia** [comment]
Thanks for the merge!

**Pull request merged**
