### PR TITLE
WMS ID: 1720: Making the changes for Master Class find fix and validate

### PR DESCRIPTION
**Pull request by avojjola**
WMS ID: 1720: Making the changes for Master Class find fix and validate, added new images and changed the description of tasks

# Add here your WMS ID
WMS ID: 1720

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ Yes] All filenames are lower case (including folders, images, files, etc.)
- [ Yes] Filenames are descriptive
- [ Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Yes ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Yes ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by rahul-tasker — CHANGES_REQUESTED** [review]
Screen Shot 2023-08-16 at 4 33 20 PM
Please use descriptive names for all image files

**Review by anooshapilli — COMMENTED** [review]
@avojjola - Please make these filenames lowercase
image

In the markdown file add, alternate text within the square brackets for each image  - [ xxx]

**Comment by Anand-GitH** [comment]
> Screen Shot 2023-08-16 at 4 33 20 PM Please use descriptive names for all image files

@rahul-tasker Hi Rahul, 

The workshop is year old and the file names you reported were resulted during migration activity by livelabs team from the learning library git to oracle live labs git repo.  So we will not be able to correct those now and will update those after the cloud world.

**Comment by Anand-GitH** [comment]
> @avojjola - Please make these filenames lowercase image
> 
> In the markdown file add, alternate text within the square brackets for each image - [ xxx]

@anooshapilli 

Hi Anoosha, 

These files are specific to swingbench application and we cant use lower case for these files. But we will make sure to include the alt text for the images. 

Thanks.

**Comment by avojjola** [comment]
Hello,

I made changes to the markdown. Should I create a new Pull Request for those changes to reflect?

Regards,
Anusha

**Comment by Anand-GitH** [comment]
@anooshapilli 

Hi Anoosha, 

We added alternate text for all the images. Kindly review and approve the PR.

Regards,
Anand

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
