### PR TITLE
WMS ID 7921 : manifest.json updates

### PR DESCRIPTION
**Pull request by dabrokwa**
# 7921

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by klazarz — APPROVED** [review]

**Comment by klazarz** [comment]
@dabrokwa please resolve the conflict mentioned above

**Comment by dabrokwa** [comment]
Hi,

What was the conflict mentioned? I don’t see it referenced?

Best,

--

[Oracle]<http://www.oracle.com/>
Desiree Abrokwa | Product Manager

From: Kevin Lazarz ***@***.***>
Date: Monday, January 23, 2023 at 4:00 AM
To: oracle-livelabs/em-omc ***@***.***>
Cc: Desiree Abrokwa ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/em-omc] manifest.json updates (PR #127)

@dabrokwa<https://urldefense.com/v3/__https:/github.com/dabrokwa__;!!ACWV5N9M2RV99hQ!MNybcqjI9iExcnjRUWU7oDWBS-eXoxHwvI2YhGg2_KPkQcwPisSwcjlsVycaqpare0f2GKlpGgYUpRAKeqeADnN8_ksZ$> please resolve the conflict mentioned above

**Comment by william-masdon-oracle** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/oracle-livelabs/em-omc/pull/127/conflicts) or the command line to resolve conflicts.
Conflicting files
enterprise-manager/emcc/em-monitoring-overview/em-monitoring-overview.md

**Comment by anooshapilli** [comment]
@dabrokwa - Please follow the steps in [Issue 3 of Troubleshooting](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=3-labs-sync-github#Troubleshooting) in step-by-step guide to resolve conflicting files.

**Comment by dabrokwa** [comment]
I had to remove some instructions to the lab which is why there are conflicts, can the latest version be accepted?

**Comment by dabrokwa** [comment]
Updated the conflicts

**Review by kamryn-v — APPROVED** [review]

**Pull request merged**
