### PR TITLE
WMS ID : 9501 - Updating changes for Management Agent

### PR DESCRIPTION
**Pull request by marniset**
# Add here your WMS ID
9501
# General requirements
1. Information in the workshop is adequate and updated - Yes
2. Code is correct and working - Yes
3. Links are correct - Yes
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Y ] All filenames are lower case (including folders, images, files, etc.)
- [ Y] Filenames are descriptive
- [ Y] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Y ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ Y] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask someone listed to add you as the workshop team?

**Comment by madhusudhanrao-ppm** [comment]
Images should have alternative text in the markdown

image

**Comment by marniset** [comment]
> Images should have alternative text in the markdown
> 
> image

**Comment by marniset** [comment]
@madhusudhanrao-ppm  I have updated the Image-alt-text to a meaningful text. Please review and share your thoughts

**Review by arabellayao — CHANGES_REQUESTED** [review]
Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask someone listed to add you as the workshop team?

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
