### PR TITLE
9501 Kubernetes and OKE Monitoring and Troubleshooting

### PR DESCRIPTION
**Pull request by vikrredd**
Live Lab OKE Monitoring via LA

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Please provide WMS ID in the title of pull request

**Comment by madhusudhanrao-ppm** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from the main into this branch.

https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest

**Comment by madhusudhanrao-ppm** [comment]
delete howtouse file

image

**Comment by arabellayao** [comment]
Followed up on 8/22.

**Comment by arabellayao** [comment]
Hi! I am closing this PR since you need to be added as a workshop team member for this workshop in WMS, and make the changes suggested by Madhu. Thanks!

**Comment by vikram264** [comment]
Hi - The review is ongoing and there are certain changes that are expected in this PR. Kindly do not change or delete or close this PR.

**Pull request closed without merging**
