### PR TITLE
WMS ID: 1700 - Hybrid Database Configuration and Compliance Management

### PR DESCRIPTION
**Pull request by shppra**

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
All image names should be lower case, please refer QA checklist document for file naming conventions

image

**Comment by shppra** [comment]
Hi Madhu:
   I did updated names to lowercase over the case, and removed previous pull and updated new ones.

Regards:
Shiva

From: Madhusudhan Rao ***@***.***>
Date: Sunday, July 17, 2022 at 8:42 PM
To: oracle-livelabs/em-omc ***@***.***>
Cc: Shiva Prasad ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/em-omc] WMS ID: 1700 - Hybrid Database Configuration and Compliance Management (PR #16)

All image names should be lower case, please refer QA checklist document for file naming conventions

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/70625227/179442064-cd0f4451-9845-4242-9c6d-8a8691286d7a.png__;!!ACWV5N9M2RV99hQ!PoBjnQIHCA3wHUpuZ9oAhj8lOoUFjBOlK1W39QxAD2ekxB_0nnAmBBaQb9hWXcmi8pdJrF60gOwvb_5fnDMLo2Vdnktj$>

**Review by arabellayao — DISMISSED** [review]
Hi! From the workshop information in WMS, the workshop URL is https://oracle-livelabs.github.io/em-omc/enterprise-manager/emcc/workshops/freetier-config-compliance/index.html.
Can you confirm that the changes in emcc-new also belong to your workshop? Thank you!

**Comment by shppra** [comment]
> Hi! From the workshop information in WMS, the workshop URL is https://oracle-livelabs.github.io/em-omc/enterprise-manager/emcc/workshops/freetier-config-compliance/index.html. Can you confirm that the changes in emcc-new also belong to your workshop? Thank you!

we are using emcc-new is being used for cloud world 2022 created by Rene's team.

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by rfontcha** [comment]
Just FYI - **emcc-new** is for OCW testing but will be renamed to "**emcc**" at version update cutover to replace the current "**emcc**". This is the devised scheme for updating an existing workshop to a new version without impacting the old version up to cutover time.

**Pull request merged**
