### PR TITLE
WMS ID 10001 

### PR DESCRIPTION
**Pull request by romitacharya**
# Add here your WMS ID
WMS ID 10001

Post OCW, there were some suggestion around user friendliness for labs. Incorporate those changes.  Added few emcli commands and corresponding images. Please approve the pull request.

Thanks,
Romit

### CODE REVIEW

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please make sure all image have descriptive alternative texts in the Markdown files for accessibility. Thanks!

**Comment by romitacharya** [comment]
Hi @arabellayao 
Yes, the files changed/modified has descriptive alternative texts.

Thanks,
Romit

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by romitacharya** [comment]
@arabellayao 
Hi Arabella,
Looks like there is some write access issue, as we are encountering this message.

This branch cannot be rebased due to conflicts
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

Can you approve this PR.

Thanks,
Romit

**Comment by madhusudhanrao-ppm** [comment]
This branch cannot be rebased due to conflicts

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please include alternative text in the following syntax: for example, 
`Maximize window`
Thanks!

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
