### PR TITLE
WMS ID: 1700 -  Hybrid Database Configuration and Compliance Management

### PR DESCRIPTION
**Pull request by shppra**
Oracle Cloud world 22 Compliance configuration modifications

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
please refer QA checklist document, image names should be all lowercase, include WMS ID in PR

image

**Comment by shppra** [comment]
include WMS ID in PR , may I know what it is. Can you explain with an example.

**Comment by arabellayao** [comment]
When you submitted a workshop request for this workshop in WMS, the workshop is assigned an ID. For example: 
Screen Shot 2022-07-15 at 2 20 22 PM

**Comment by shppra** [comment]
Updating image names to lower cases, will reopen new pull request.

**Pull request closed without merging**
