### PR TITLE
WMS 10001: Changes wrt OCW23

### PR DESCRIPTION
**Pull request by romitacharya**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by romitacharya** [comment]
Please approve this PR. This is the patching lab for EM

**Review by kamryn-v — DISMISSED** [review]

**Comment by kamryn-v** [comment]
@romitacharya please resolve the conflicts

**Comment by ZRTalke** [comment]
Hi @romitacharya 

I'm still seeing conflicts for 
enterprise-manager/emcc/em-fleet-maintenance-patching-ui/em-fleet-maintenance-patching-ui.md
enterprise-manager/emcc/fleet-maintenance-hub/em-fleet-maintenance-hub.md

I can approve your pull request once they are resolved

**Comment by anooshapilli** [comment]
@romitacharya - Please add alternative text to the images as in Lab 4 Task 4 Step 2 code block in the guide - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=4-labs-markdown-develop-content#Task4:Linktoabsolutepathimages)

**Pull request closed without merging**
