### PR TITLE
WMS ID: 1700 - Hybrid Database Configuration and Compliance Management 

### PR DESCRIPTION
**Pull request by shppra**
manifest.json changes for configuration-compliance newly created directories for OCW2022, Added more info in markdown files to provide info on webinars, blog for lab participants

### CODE REVIEW

**Review by shppra — COMMENTED** [review]
manifest.json file changes has been incorporated in manifest.json file for enterprise-manager/emcc/workshops/ocw-desktop-config-compliance new folder

**Review by shppra — COMMENTED** [review]
manifest.json file changes has been incorporated in manifest.json file for enterprise-manager/emcc/workshops/ocw-desktop-config-compliance,   ocw-livelabs-config-compliance and ocw-freetier-config-compliance folders

**Review by arabellayao — COMMENTED** [review]
Hi! Can you correct that information? Thanks!
Screen Shot 2022-08-29 at 12 39 35 PM

**Comment by shppra** [comment]
Made modifcations. Good to go.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
