### PR TITLE
Modifying the estimated time and adding images for better understanding

### PR DESCRIPTION
**Pull request by SindhujaReddy-VT**
Adding lab Ops Insights for HeatWave MySQL

WMS ID: 11543

I am a new Product Manager for HeatWave MySQL and have not been added to WMS ID:11543 and workflow management system yet. Please kindly approve the PR.

[ Yes] All filenames are lower case (including folders, images, files, etc.)
[ Yes] Filenames are descriptive
[ Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
[Yes ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
[Yes] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @SindhujaReddy-VT, please resolve the conflicts

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @SindhujaReddy-VT, please check the path for the Lab 6 in the manifest.json file

**Comment by SindhujaReddy-VT** [comment]
> Hi @SindhujaReddy-VT, please resolve the conflicts

Hi @anacoman11 , I have resolved the issues. Kindly approve the pull request.

**Review by anacoman11 — APPROVED** [review]

**Review by carmenberdant1 — DISMISSED** [review]

**Comment by SindhujaReddy-VT** [comment]
Added a new pull request because of conflicts

**Pull request closed without merging**
