### PR TITLE
#7921: Runbooks to EM Monitoring LiveLab

### PR DESCRIPTION
**Pull request by dabrokwa**
Runbooks to EM Monitoring LiveLab

### CODE REVIEW

**Comment by dabrokwa** [comment]
Edits to EM Monitoring Quick Tour LiveLab

**Comment by dabrokwa** [comment]
WMS: 7921

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! All images' filenames should be descriptive, instead of using step numbers. Thanks!

**Comment by arabellayao** [comment]
Followed up on 08/03.

**Review by kamryn-v — APPROVED** [review]

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
