### PR TITLE
WMS ID - 1681 - Multitenant Lab Changes after OCW Feedback

### PR DESCRIPTION
**Pull request by srmouli**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@srmouli - Could you update the PR with the WMS ID of the workshop?

**Comment by srmouli** [comment]
Updated the WMS ID in the PR name

**Comment by anooshapilli** [comment]
@rfontcha - Could you confirm if these changes can be approved?

**Review by rfontcha — APPROVED** [review]
Please merge

**Comment by srmouli** [comment]
@Anand-GitH 
Anand, this change is in line with https://confluence.oraclecorp.com/confluence/display/SYSMGMTPM/OCW22+HOL+improvement+scrum+list

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
