### PR TITLE
9501  Kubernetes Monitoring and Troubleshooting

### PR DESCRIPTION
**Pull request by vikrredd**
# 9501

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramumg — CHANGES_REQUESTED** [review]
@vikrredd, 

In the manifest for cloud world, you need to have the get help section and the ocw support section. Please change the get help part to support. 

Thank you, 
Ramu

**Comment by vikrredd** [comment]
@ramumg : I have made the change you suggested.

**Review by ramumg — CHANGES_REQUESTED** [review]
@vikrredd, 
- you are missing the prerequisites section in some of your md files 
- you also need the help section before the support section in your manifests for cloud world. 

Thank you, 
Ramu

**Comment by vikrredd** [comment]
@ramumg - All the labs in the workshop are independent thus we have not added the prerequisites.

> you also need the help section before the support section in your manifests for cloud world
- Can you direct me to the workshop with the mentioned structure for easier implementation of the changes?

**Comment by anooshapilli** [comment]
@vikrredd - You need to add the need help before the ocw support lab like this - https://oracle-livelabs.github.io/apex/social-media-app/workshops/ocw23-freetier/index.html?lab=need-help-freetier

You can use this link to add in the manifest.json file - https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md

**Comment by vikrredd** [comment]
Need Help Section is added in the manifest.json

**Review by ramumg — APPROVED** [review]

**Pull request merged**
