### PR TITLE
WMS 9522: live lab for EBS monitoring using Logging analytics

### PR DESCRIPTION
**Pull request by kumar-ola**
WMS 9522

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all images’ filenames are lower case
2. freetier/manifest.json should use this file as the "Need Help?" lab: "https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md"

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all images’ filenames are lower case
2. Correct the freetier/manifest.json. Refer to this file for example: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/manifest.json
Thanks!

**Comment by GurusamyPoosamalai** [comment]
Updated images filename to lowercase and updated freetier/manifest.json

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please use this file for the “Need Help?” Lab for freetier: “https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md” instead of “https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md”

**Comment by GurusamyPoosamalai** [comment]
> Hi! Please use this file for the “Need Help?” Lab for freetier: “[https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md”](https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md%E2%80%9D) instead of “[https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md”](https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md%E2%80%9D)

Thanks for reviewing, I have updated now, Please help review.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
