### PR TITLE
Oracle Cloud World 22 - changes to livelab instructions

### PR DESCRIPTION
**Pull request by romitacharya**
Oracle Cloud World 22 - changes to livelab instructions
Live Lab Ids are - 
10001  Automate Database Patching Using the Oracle Enterprise Manager Fleet Maintenance UI
10002  Automate Database Upgrades Using the Oracle Enterprise Manager Fleet Maintenance UI

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
please include WMS ID in the title of the pull request, file names should be all lowercase, and refer QA checklist document in WMS

image

**Comment by romitacharya** [comment]
> please include WMS ID in the title of the pull request, file names should be all lowercase, and refer QA checklist document in WMS
> 
> image

Hi Madhu,

Changes done as per your suggestion. Could you please review them again. All these files which are part of the lab follow the naming convention. You may find 2 files which are in upper case , but they are purely as a backup file. Hope you will still approve the merge. I had to keep this to distinguish them among many image files that I have. Many new images files have been added and older ones replaced as we have upgraded the base image to RU7 and its important that corresponding changes are done to the images ( wherever applicable)

Thansk,
Romit

**Review by arabellayao — COMMENTED** [review]
Hi! Some images in em-fleet-maintenance-patching-ui, em-fleet-maintenance-upgrade-ui still use underscores and uppercase letters. Please update their names to satisfy with the standards. Thank you!

**Comment by romitacharya** [comment]
> Hi! Some images in em-fleet-maintenance-patching-ui, em-fleet-maintenance-upgrade-ui still use underscores and uppercase letters. Please update their names to satisfy with the standards. Thank you!

Hi Arabella,  Can you please highlights which ones are these. I had validated before updating the PR. File name match the standards now.

Thanks,
Romit

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
