### PR TITLE
WMS ID 1681 - Multitenant Lab

### PR DESCRIPTION
**Pull request by srmouli**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@srmouli - Can you please rename Lab to Task in the markdown file?

**Comment by srmouli** [comment]
> @srmouli - Can you please rename Lab to Task in the markdown file?
 @anooshapilli  This was a suggestion that Steve Lemme has suggested. It was initially named Task, but he suggested renaming them to Lab. Could you please check with him? 
 @shppra @Anand-GitH

**Comment by stevenlemme** [comment]
@anooshapilli  initially in LiveLabs Task was a term that was OK. Then it was communicated on a LiveLabs call NOT to use the term Task. So can you confirm that use of the term Task is a standard and OK for authors to use?  Some Database team workshops use Task and other do not, so that's why were asking so we don't have to change it again. Thank you

**Comment by anooshapilli** [comment]
@srmouli @stevenlemme - I see the contents in em-multitenant-lifecycle-automation.md markdown file is Lab 3 in the published workshop - https://github.com/srmouli/em-omc/blob/main/enterprise-manager/emcc/workshops/freetier-lifecycle/manifest.json
Each lab will have collapsible tasks like Task X : title. This is the correct format - https://oracle-livelabs.github.io/em-omc/enterprise-manager/emcc/workshops/freetier-lifecycle/index.html?lab=em-multitenant-lifecycle-automation
A Lab is used only in the manifest.json file that is displayed on the left menu.
So please update them to task.

**Comment by srmouli** [comment]
@anooshapilli Updated 'Lab' with 'Task'.

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
